#!/bin/bash

# Install Snap Applications
function install_snap_apps {
	NAME="Snap Applications"
	echo_message title "Starting installation of ${NAME,,}..."
	status="0"
	while [ "$status" -eq 0 ]; do
		# Draw window
		SNAPS=$(eval `resize` && whiptail \
			--notags \
			--title "Install $NAME" \
			--menu "\nWhat ${NAME,,} would you like to install?" install_snap_sublime\
			--ok-button "Install" \
			--cancel-button "Go Back" \
			$LINES $COLUMNS $(( $LINES - 12 )) \
			'install_snap_bruno'        'Bruno API-Client' \
			'install_snap_code'         'VSCode' \
			'install_snap_firefox'      'Firefox' \
			'install_snap_gimp'      		'GIMP' \
			'install_snap_intellij'     'IntelliJ IDEA Community Edition' \
			'install_snap_pycharm'      'Pycharm Community Edition' \
			'install_snap_jq'      			'jq command' \
			'install_snap_telegram' 		'telegram desktop' \
			'install_snap_inkscape'     'Inkscape' \
			3>&1 1>&2 2>&3)

		case "${SNAPS}" in
			install_snap_bruno)
				# install Bruno
				install_snap_package "Bruno API Client" "bruno" install_snap_apps
				;;
			install_snap_code)
				# install Code
				install_snap_package "VSCode" "code" "--classic" install_snap_apps
				;;
			install_snap_firefox)
				# install Firefox
				install_snap_package "Mozilla Firefox" "firefox" install_snap_apps
				;;
			install_snap_gimp)
				# install Firefox
				install_snap_package "GIMP" "gimp" install_snap_apps
				;;
			install_snap_intellij)
				# install Firefox
				install_snap_package "IntelliJ IDEA Community Edition" "intellij-idea-community" "--classic" install_snap_apps
				;;
			install_snap_pycharm)
				# install Firefox
				install_snap_package "Pycharm Community Edition" "pycharm-community" "--classic" install_snap_apps
				;;
			install_snap_jq)
				# install Firefox
				install_snap_package "jq command" "jq" install_snap_apps
				;;
			install_snap_telegram)
				# install Firefox
				install_snap_package "Telegram Desktop" "telegram-desktop" install_snap_apps
				;;
			install_snap_inkscape)
				# install Inkscape
				install_snap_package "Inkscape" "inkscape" install_snap_apps
				;;
			*) 
				# cancel
				echo_message info "Returning..."
				status=1
				main
			;;
		esac
	done
}